'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import type { Deduction, DeductionTaxTreatment, PaycheckInput, PaycheckResult } from '../calculator/types.ts';
import { calculatePaycheck } from '../calculator/index.ts';
import { comparePayFrequencies, periodsPerYear } from '../calculator/periods.ts';
import { currency, wholeCurrency } from '../site/format.ts';
import { verifiedStatePages } from '../site/states.ts';
import { stateCalculators } from '../calculator/states/index.ts';

function track(event: string, data?: Record<string, string>) {
  if (typeof window === 'undefined') return;
  const w = window as typeof window & { gtag?: (...args: unknown[]) => void; umami?: { track: (name: string, data?: Record<string, string>) => void } };
  w.gtag?.('event', event, data);
  w.umami?.track(event, data);
}

const statusLabels = { single: 'Single', married_joint: 'Married filing jointly', married_separate: 'Married filing separately', head_of_household: 'Head of household' };
const deductionLabels: Record<Deduction['kind'], string> = { '401k': 'Traditional 401(k)', hsa: 'HSA', fsa: 'FSA', health: 'Health insurance', dental: 'Dental', vision: 'Vision', custom: 'Custom deduction' };
const noReduction: DeductionTaxTreatment = { federalIncomeTax: false, socialSecurity: false, medicare: false, stateIncomeTax: false, localIncomeTax: false };

function InputField({ label, value, onChange, prefix = '$', step = '0.01' }: { label: string; value: number; onChange: (value: number) => void; prefix?: string; step?: string }) {
  return <label className="field"><span>{label}</span><span className="input-wrap">{prefix && <span>{prefix}</span>}<input type="number" min="0" step={step} value={value} onChange={event => onChange(Number(event.target.value))} /></span></label>;
}

function OptionalInputField({ label, value, onChange }: { label: string; value?: number; onChange: (value?: number) => void }) {
  return <label className="field"><span>{label}</span><span className="input-wrap"><span>$</span><input type="number" min="0" step="0.01" value={value ?? ''} placeholder="Projected" onChange={event => onChange(event.target.value === '' ? undefined : Number(event.target.value))} /></span></label>;
}

function ResultLine({ label, amount, gross = false }: { label: string; amount: number; gross?: boolean }) {
  return <div className="result-line"><span>{label}</span><strong>{gross ? currency(amount) : `−${currency(amount)}`}</strong></div>;
}

export function Calculator({ initialInput, initialResult }: { initialInput: PaycheckInput; initialResult: PaycheckResult }) {
  useEffect(() => { track('calculator_view'); }, []);
  const availableStates = verifiedStatePages.filter(page => stateCalculators[initialInput.taxYear]?.[page.code]?.metadata.status === 'verified');
  const [input, setInput] = useState(initialInput);
  const [advanced, setAdvanced] = useState(false);
  const [newDeduction, setNewDeduction] = useState<Deduction['kind']>('401k');
  const [shareStatus, setShareStatus] = useState('');
  const started = useRef(false);
  const resultRef = useRef<HTMLDivElement>(null);
  const calculated = useMemo(() => {
    try { return { result: calculatePaycheck(input), error: '' }; }
    catch (error) { return { result: initialResult, error: error instanceof Error ? error.message : 'Calculation unavailable' }; }
  }, [input, initialResult]);
  const { result, error } = calculated;
  const periodResults = useMemo(() => error ? undefined : comparePayFrequencies(input), [input, error]);
  const update = (next: PaycheckInput) => {
    if (!started.current) { track('calculator_started'); started.current = true; }
    setShareStatus('');
    setInput(next);
  };
  const updateFederal = (key: keyof PaycheckInput['federal'], value: string | number | boolean) => update({ ...input, federal: { ...input.federal, [key]: value } });
  const updateStateOption = (key: string, value: number | boolean) => update({ ...input, stateOptions: { ...input.stateOptions, [key]: value } });
  const setCompensation = (key: string, value: number) => update({ ...input, compensation: { ...input.compensation, [key]: value } as PaycheckInput['compensation'] });
  const addDeduction = () => {
    const kind = newDeduction;
    const deduction: Deduction = { id: `${kind}-${Date.now()}`, label: deductionLabels[kind], kind, amount: 0, unit: 'dollars', timing: 'pre_tax', ...(kind === 'custom' ? { treatment: noReduction } : {}) };
    update({ ...input, deductions: [...input.deductions, deduction] });
  };
  const updateDeduction = (id: string, change: Partial<Deduction>) => update({ ...input, deductions: input.deductions.map(deduction => deduction.id === id ? { ...deduction, ...change } : deduction) });
  const submit = () => { if (!error) { track('calculator_completed', { state: input.location.state, frequency: input.payFrequency }); resultRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }); } };
  const shareResult = async () => {
    const stateName = verifiedStatePages.find(page => page.code === input.location.state)?.name ?? input.location.state;
    const summary = `${stateName} estimated ${input.payFrequency} take-home pay: ${currency(result.netPay)} from ${currency(result.grossPay)} gross. Estimated paycheck — not tax advice.`;
    try {
      if (navigator.share) await navigator.share({ title: 'TheTax.us paycheck estimate', text: summary, url: window.location.href });
      else { await navigator.clipboard.writeText(`${summary} ${window.location.href}`); setShareStatus('Result copied to clipboard.'); }
      track('result_shared', { state: input.location.state, frequency: input.payFrequency });
    } catch (shareError) {
      if (shareError instanceof DOMException && shareError.name === 'AbortError') return;
      setShareStatus('Sharing is unavailable in this browser.');
    }
  };
  const percent = result.grossPay > 0 ? Math.round(result.netPay / result.grossPay * 100) : 0;
  const deductions = result.deductions.filter(item => item.amount > 0);
  const rows = [
    { label: 'Federal withholding', amount: result.federal.incomeTaxWithholding },
    { label: 'Social Security', amount: result.federal.socialSecurity },
    { label: 'Medicare', amount: result.federal.medicare },
    { label: 'Additional Medicare', amount: result.federal.additionalMedicare },
    { label: `${verifiedStatePages.find(page => page.code === input.location.state)?.name ?? 'State'} withholding`, amount: result.state.incomeTaxWithholding },
    { label: input.location.city ? `${input.location.city} withholding` : 'Local withholding', amount: result.local.withholding },
  ].filter(row => row.amount > 0);

  return <div className="calculator-grid">
    <section className="calculator-card inputs-card" aria-label="Your pay">
      <div className="card-heading"><span className="step">01</span><div><p className="eyebrow">Your pay</p><h2>Tell us about your paycheck</h2></div></div>
      <div className="segmented"><button type="button" className={input.compensation.type === 'salary' ? 'active' : ''} onClick={() => { track('salary_hourly_switch', { to: 'salary' }); update({ ...input, compensation: { type: 'salary', annualSalary: 100000 } }); }}>Salary</button><button type="button" className={input.compensation.type === 'hourly' ? 'active' : ''} onClick={() => { track('salary_hourly_switch', { to: 'hourly' }); update({ ...input, compensation: { type: 'hourly', hourlyRate: 30, regularHours: 80, overtimeHours: 0, overtimeMultiplier: 1.5 } }); }}>Hourly</button></div>
      {input.compensation.type === 'salary' ? <InputField label="Annual salary" value={input.compensation.annualSalary} onChange={value => setCompensation('annualSalary', value)} /> : <><InputField label="Hourly rate" value={input.compensation.hourlyRate} onChange={value => setCompensation('hourlyRate', value)} /><InputField label="Regular hours per pay period" prefix="" value={input.compensation.regularHours} onChange={value => setCompensation('regularHours', value)} /></>}
      <div className="field-row"><label className="field"><span>Location</span><select value={input.location.state} onChange={event => { const state = event.target.value; track('state_changed', { state }); update({ ...input, location: { state } }); }}>{availableStates.map(page => <option key={page.code} value={page.code}>{page.name}</option>)}</select></label><label className="field"><span>Filing status</span><select value={input.federal.filingStatus} onChange={event => updateFederal('filingStatus', event.target.value)}>{Object.entries(statusLabels).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label></div>
      <label className="field"><span>Pay frequency</span><select value={input.payFrequency} onChange={event => { track('pay_frequency_changed', { frequency: event.target.value }); update({ ...input, payFrequency: event.target.value as PaycheckInput['payFrequency'] }); }}><option value="weekly">Weekly</option><option value="biweekly">Biweekly</option><option value="semimonthly">Semi-monthly</option><option value="monthly">Monthly</option></select></label>
      <button className="advanced-toggle" type="button" aria-expanded={advanced} onClick={() => { if (!advanced) track('advanced_opened'); setAdvanced(!advanced); }}>Advanced options <span>{advanced ? '−' : '+'}</span></button>
      {advanced && <div className="advanced-panel">
        <h3>Federal W-4</h3><label className="checkbox"><input type="checkbox" checked={input.federal.multipleJobs} onChange={event => updateFederal('multipleJobs', event.target.checked)} />Step 2 multiple jobs checkbox</label>
        <div className="field-row"><InputField label="Dependent credits, annual" value={input.federal.dependentCredits} onChange={value => updateFederal('dependentCredits', value)} /><InputField label="Other income, annual" value={input.federal.otherIncome} onChange={value => updateFederal('otherIncome', value)} /></div>
        <div className="field-row"><InputField label="Other deductions, annual" value={input.federal.deductions} onChange={value => updateFederal('deductions', value)} /><InputField label="Extra withholding per paycheck" value={input.federal.extraWithholding} onChange={value => updateFederal('extraWithholding', value)} /></div>
        <label className="checkbox"><input type="checkbox" checked={input.federal.exempt} onChange={event => updateFederal('exempt', event.target.checked)} />Exempt from federal income tax withholding</label>
        {input.compensation.type === 'hourly' && <><h3>Hourly earnings</h3><div className="field-row"><InputField label="Overtime hours" prefix="" value={input.compensation.overtimeHours ?? 0} onChange={value => setCompensation('overtimeHours', value)} /><InputField label="Overtime multiplier" prefix="×" value={input.compensation.overtimeMultiplier ?? 1.5} onChange={value => setCompensation('overtimeMultiplier', value)} /></div></>}
        <h3>Pay date and year-to-date</h3><label className="field"><span>Pay date</span><input type="date" min={`${input.taxYear}-01-01`} max={`${input.taxYear}-12-31`} value={input.payDate} onChange={event => update({ ...input, payDate: event.target.value })} /></label><p className="help">Leave YTD blank to use a pay-date projection.</p><div className="field-row"><OptionalInputField label="YTD gross wages" value={input.ytd?.grossWages} onChange={value => update({ ...input, ytd: { ...input.ytd, grossWages: value } })} /><OptionalInputField label="YTD Social Security wages" value={input.ytd?.socialSecurityWages} onChange={value => update({ ...input, ytd: { ...input.ytd, socialSecurityWages: value } })} /></div><div className="field-row"><OptionalInputField label="YTD Medicare wages" value={input.ytd?.medicareWages} onChange={value => update({ ...input, ytd: { ...input.ytd, medicareWages: value } })} />{input.location.state === 'RI' && <OptionalInputField label="YTD Rhode Island TDI wages" value={input.ytd?.stateWages} onChange={value => update({ ...input, ytd: { ...input.ytd, stateWages: value } })} />}</div>
        <h3>Paycheck deductions</h3><div className="add-row"><select value={newDeduction} onChange={event => setNewDeduction(event.target.value as Deduction['kind'])}>{Object.entries(deductionLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><button type="button" onClick={addDeduction}>Add deduction</button></div>
        {input.deductions.map(deduction => <div className="deduction-row" key={deduction.id}><strong>{deduction.label}</strong><div className="field-row"><InputField label="Amount" prefix="" value={deduction.amount} onChange={value => updateDeduction(deduction.id, { amount: value })} /><label className="field"><span>Unit</span><select value={deduction.unit} onChange={event => updateDeduction(deduction.id, { unit: event.target.value as Deduction['unit'] })}><option value="dollars">$/paycheck</option><option value="percent">% of gross</option></select></label></div><label className="field"><span>Timing</span><select value={deduction.timing} onChange={event => updateDeduction(deduction.id, { timing: event.target.value as Deduction['timing'] })}><option value="pre_tax">Pre-tax</option><option value="post_tax">Post-tax</option></select></label>{deduction.kind === 'custom' && <div className="custom-taxes"><span>Reduces taxable wages for:</span>{Object.entries({ federalIncomeTax: 'Federal income tax', socialSecurity: 'Social Security', medicare: 'Medicare', stateIncomeTax: 'State income tax', localIncomeTax: 'Local income tax' }).map(([key, label]) => <label className="checkbox" key={key}><input type="checkbox" checked={!!deduction.treatment?.[key as keyof DeductionTaxTreatment]} onChange={event => updateDeduction(deduction.id, { treatment: { ...deduction.treatment!, [key]: event.target.checked } })} />{label}</label>)}</div>}<button type="button" className="text-button" onClick={() => update({ ...input, deductions: input.deductions.filter(item => item.id !== deduction.id) })}>Remove</button></div>)}
        {input.location.state === 'CA' && <><h3>California DE 4</h3><div className="field-row"><InputField label="Regular allowances" prefix="" step="1" value={Number(input.stateOptions?.caAllowances ?? 0)} onChange={value => updateStateOption('caAllowances', value)} /><InputField label="Estimated deduction allowances" prefix="" step="1" value={Number(input.stateOptions?.caDeductionAllowances ?? 0)} onChange={value => updateStateOption('caDeductionAllowances', value)} /></div><InputField label="Extra CA withholding" value={Number(input.stateOptions?.caExtraWithholding ?? 0)} onChange={value => updateStateOption('caExtraWithholding', value)} /></>}
        {input.location.state === 'IL' && <><h3>Illinois IL-W-4</h3><div className="field-row"><InputField label="Line 1 allowances" prefix="" step="1" value={Number(input.stateOptions?.ilLine1Allowances ?? 0)} onChange={value => updateStateOption('ilLine1Allowances', value)} /><InputField label="Line 2 allowances" prefix="" step="1" value={Number(input.stateOptions?.ilLine2Allowances ?? 0)} onChange={value => updateStateOption('ilLine2Allowances', value)} /></div><InputField label="Extra Illinois withholding" value={Number(input.stateOptions?.ilExtraWithholding ?? 0)} onChange={value => updateStateOption('ilExtraWithholding', value)} /></>}
        {input.location.state === 'IN' && <><h3>Indiana WH-4</h3><div className="field-row"><InputField label="Personal exemptions" prefix="" step="1" value={Number(input.stateOptions?.inPersonalExemptions ?? 0)} onChange={value => updateStateOption('inPersonalExemptions', value)} /><InputField label="Dependent exemptions" prefix="" step="1" value={Number(input.stateOptions?.inDependentExemptions ?? 0)} onChange={value => updateStateOption('inDependentExemptions', value)} /></div><div className="field-row"><InputField label="First-time dependent exemptions" prefix="" step="1" value={Number(input.stateOptions?.inFirstTimeDependentExemptions ?? 0)} onChange={value => updateStateOption('inFirstTimeDependentExemptions', value)} /><InputField label="Adopted child exemptions" prefix="" step="1" value={Number(input.stateOptions?.inAdoptedExemptions ?? 0)} onChange={value => updateStateOption('inAdoptedExemptions', value)} /></div><p className="help">Indiana county income tax is not included.</p></>}
        {input.location.state === 'MI' && <><h3>Michigan MI-W4</h3><InputField label="Personal and dependency exemptions" prefix="" step="1" value={Number(input.stateOptions?.miExemptions ?? 0)} onChange={value => updateStateOption('miExemptions', value)} /><p className="help">Michigan city income taxes are not included.</p></>}
        {input.location.state === 'NC' && <><h3>North Carolina NC-4</h3><InputField label="Withholding allowances" prefix="" step="1" value={Number(input.stateOptions?.ncAllowances ?? 0)} onChange={value => updateStateOption('ncAllowances', value)} /></>}
        {input.location.state === 'GA' && <><h3>Georgia G-4</h3><InputField label="Dependent allowances" prefix="" step="1" value={Number(input.stateOptions?.gaDependents ?? 0)} onChange={value => updateStateOption('gaDependents', value)} /><label className="checkbox"><input type="checkbox" checked={!!input.stateOptions?.gaBothSpousesWorking} onChange={event => updateStateOption('gaBothSpousesWorking', event.target.checked)} />Both spouses work (married filing jointly)</label></>}
        {input.location.state === 'AZ' && <><h3>Arizona A-4</h3><label className="field"><span>Withholding election</span><select value={Number(input.stateOptions?.azWithholdingRate ?? .02)} onChange={event => updateStateOption('azWithholdingRate', Number(event.target.value))}>{[0, 0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035].map(rate => <option key={rate} value={rate}>{(rate * 100).toFixed(1)}%</option>)}</select></label><InputField label="Extra Arizona withholding" value={Number(input.stateOptions?.azExtraWithholding ?? 0)} onChange={value => updateStateOption('azExtraWithholding', value)} /></>}
        {input.location.state === 'OH' && <><h3>Ohio exemptions</h3><InputField label="Withholding exemptions" prefix="" step="1" value={Number(input.stateOptions?.ohExemptions ?? 0)} onChange={value => updateStateOption('ohExemptions', value)} /><p className="help">Municipal and school district income taxes are not included.</p></>}
        {input.location.state === 'VA' && <><h3>Virginia VA-4</h3><div className="field-row"><InputField label="Personal and dependent exemptions" prefix="" step="1" value={Number(input.stateOptions?.vaPersonalExemptions ?? 0)} onChange={value => updateStateOption('vaPersonalExemptions', value)} /><InputField label="Age 65 or blind exemptions" prefix="" step="1" value={Number(input.stateOptions?.vaAgeBlindExemptions ?? 0)} onChange={value => updateStateOption('vaAgeBlindExemptions', value)} /></div></>}
        {input.location.state === 'MA' && <><h3>Massachusetts M-4</h3><div className="field-row"><InputField label="Withholding exemptions" prefix="" step="1" value={Number(input.stateOptions?.maExemptions ?? 0)} onChange={value => updateStateOption('maExemptions', value)} /><InputField label="Blind people (employee or spouse)" prefix="" step="1" value={Number(input.stateOptions?.maBlindPeople ?? 0)} onChange={value => updateStateOption('maBlindPeople', value)} /></div><InputField label="Extra Massachusetts withholding" value={Number(input.stateOptions?.maExtraWithholding ?? 0)} onChange={value => updateStateOption('maExtraWithholding', value)} /><label className="checkbox"><input type="checkbox" checked={!!input.stateOptions?.maPflNotCovered} onChange={event => updateStateOption('maPflNotCovered', event.target.checked)} />This job is not covered by Massachusetts PFML</label></>}
        {input.location.state === 'CO' && <><h3>Colorado DR 0004</h3><InputField label="Annual withholding allowance" value={Number(input.stateOptions?.coAnnualAllowance ?? (input.federal.filingStatus === 'married_joint' ? 11000 : 5500))} onChange={value => updateStateOption('coAnnualAllowance', value)} /><InputField label="Extra Colorado withholding" value={Number(input.stateOptions?.coExtraWithholding ?? 0)} onChange={value => updateStateOption('coExtraWithholding', value)} /><label className="checkbox"><input type="checkbox" checked={Boolean(input.stateOptions?.coExempt ?? (input.federal.exempt && input.stateOptions?.coAnnualAllowance === undefined))} onChange={event => updateStateOption('coExempt', event.target.checked)} />Exempt from Colorado income tax withholding</label><p className="help">Local occupational privilege taxes are not included.</p></>}
        {input.location.state === 'MO' && <><h3>Missouri MO W-4</h3><label className="checkbox"><input type="checkbox" checked={!!input.stateOptions?.moSpouseDoesNotWork} onChange={event => updateStateOption('moSpouseDoesNotWork', event.target.checked)} />Married, spouse does not work</label><InputField label="Extra Missouri withholding" value={Number(input.stateOptions?.moExtraWithholding ?? 0)} onChange={value => updateStateOption('moExtraWithholding', value)} /><p className="help">Kansas City and St. Louis earnings taxes are not included.</p></>}
        {input.location.state === 'IA' && <><h3>Iowa IA W-4</h3><label className="checkbox"><input type="checkbox" checked={!!input.stateOptions?.iaSpouseEarnedIncome} onChange={event => updateStateOption('iaSpouseEarnedIncome', event.target.checked)} />Married, spouse has earned income</label><div className="field-row"><InputField label="Annual allowance amount" value={Number(input.stateOptions?.iaAnnualAllowance ?? 0)} onChange={value => updateStateOption('iaAnnualAllowance', value)} /><InputField label="Extra Iowa withholding" value={Number(input.stateOptions?.iaExtraWithholding ?? 0)} onChange={value => updateStateOption('iaExtraWithholding', value)} /></div></>}
        {input.location.state === 'MS' && <><h3>Mississippi Form 89-350</h3><label className="checkbox"><input type="checkbox" checked={!!input.stateOptions?.msOneSpouseEmployed} onChange={event => updateStateOption('msOneSpouseEmployed', event.target.checked)} />Married, only one spouse works</label><div className="field-row"><InputField label="Annual exemption amount" value={Number(input.stateOptions?.msExemptionAmount ?? 0)} onChange={value => updateStateOption('msExemptionAmount', value)} /><InputField label="Extra Mississippi withholding" value={Number(input.stateOptions?.msExtraWithholding ?? 0)} onChange={value => updateStateOption('msExtraWithholding', value)} /></div></>}
        {input.location.state === 'SC' && <><h3>South Carolina SC W-4</h3><div className="field-row"><InputField label="Personal allowances" prefix="" step="1" value={Number(input.stateOptions?.scAllowances ?? 0)} onChange={value => updateStateOption('scAllowances', value)} /><InputField label="Extra South Carolina withholding" value={Number(input.stateOptions?.scExtraWithholding ?? 0)} onChange={value => updateStateOption('scExtraWithholding', value)} /></div></>}
        {input.location.state === 'AL' && <><h3>Alabama A-4</h3><InputField label="Dependents other than spouse" prefix="" step="1" value={Number(input.stateOptions?.alDependents ?? 0)} onChange={value => updateStateOption('alDependents', value)} /><label className="checkbox"><input type="checkbox" checked={!!input.stateOptions?.alZeroExemption} onChange={event => updateStateOption('alZeroExemption', event.target.checked)} />Claim zero exemptions</label><p className="help">Local occupational taxes are not included.</p></>}
        {input.location.state === 'KS' && <><h3>Kansas K-4</h3><InputField label="Dependents" prefix="" step="1" value={Number(input.stateOptions?.ksDependents ?? 0)} onChange={value => updateStateOption('ksDependents', value)} /><InputField label="Extra Kansas withholding" value={Number(input.stateOptions?.ksExtraWithholding ?? 0)} onChange={value => updateStateOption('ksExtraWithholding', value)} /><label className="checkbox"><input type="checkbox" checked={!!input.stateOptions?.ksNoCertificate} onChange={event => updateStateOption('ksNoCertificate', event.target.checked)} />No Kansas K-4 on file</label></>}
        {input.location.state === 'WV' && <><h3>West Virginia IT-104</h3><InputField label="Exemptions" prefix="" step="1" value={Number(input.stateOptions?.wvExemptions ?? 0)} onChange={value => updateStateOption('wvExemptions', value)} /><InputField label="Extra West Virginia withholding" value={Number(input.stateOptions?.wvExtraWithholding ?? 0)} onChange={value => updateStateOption('wvExtraWithholding', value)} /><label className="checkbox"><input type="checkbox" checked={!!input.stateOptions?.wvOneEarner} onChange={event => updateStateOption('wvOneEarner', event.target.checked)} />Request one-earner/one-job schedule</label></>}
        {input.location.state === 'NJ' && <><h3>New Jersey NJ-W4</h3><div className="field-row"><InputField label="Exemptions" prefix="" step="1" value={Number(input.stateOptions?.njExemptions ?? 0)} onChange={value => updateStateOption('njExemptions', value)} /><InputField label="Extra New Jersey withholding" value={Number(input.stateOptions?.njExtraWithholding ?? 0)} onChange={value => updateStateOption('njExtraWithholding', value)} /></div><label className="field"><span>Withholding rate table</span><select value={String(input.stateOptions?.njRate ?? '')} onChange={event => { const stateOptions = { ...input.stateOptions }; if (event.target.value) stateOptions.njRate = event.target.value; else delete stateOptions.njRate; update({ ...input, stateOptions }); }}><option value="">Default for filing status</option><option value="A">Rate A</option><option value="B">Rate B</option></select></label><label className="checkbox"><input type="checkbox" checked={!!input.stateOptions?.njExempt} onChange={event => updateStateOption('njExempt', event.target.checked)} />Exempt from New Jersey income tax withholding</label><p className="help">NJ-W4 Rates C, D, and E are not yet supported.</p></>}
        {input.location.state === 'WI' && <><h3>Wisconsin WT-4</h3><div className="field-row"><InputField label="Exemptions" prefix="" step="1" value={Number(input.stateOptions?.wiExemptions ?? 0)} onChange={value => updateStateOption('wiExemptions', value)} /><InputField label="Extra Wisconsin withholding" value={Number(input.stateOptions?.wiExtraWithholding ?? 0)} onChange={value => updateStateOption('wiExtraWithholding', value)} /></div><label className="checkbox"><input type="checkbox" checked={!!input.stateOptions?.wiExempt} onChange={event => updateStateOption('wiExempt', event.target.checked)} />Exempt from Wisconsin income tax withholding</label></>}
        {input.location.state === 'OK' && <><h3>Oklahoma OK-W-4</h3><div className="field-row"><InputField label="Allowances" prefix="" step="1" value={Number(input.stateOptions?.okAllowances ?? 0)} onChange={value => updateStateOption('okAllowances', value)} /><InputField label="Extra Oklahoma withholding" value={Number(input.stateOptions?.okExtraWithholding ?? 0)} onChange={value => updateStateOption('okExtraWithholding', value)} /></div><label className="checkbox"><input type="checkbox" checked={!!input.stateOptions?.okSingleRate} onChange={event => updateStateOption('okSingleRate', event.target.checked)} />Married, use higher single withholding schedule</label><label className="checkbox"><input type="checkbox" checked={!!input.stateOptions?.okExempt} onChange={event => updateStateOption('okExempt', event.target.checked)} />Exempt from Oklahoma income tax withholding</label></>}
        {input.location.state === 'ND' && <><h3>North Dakota withholding</h3><InputField label="Extra North Dakota withholding" value={Number(input.stateOptions?.ndExtraWithholding ?? 0)} onChange={value => updateStateOption('ndExtraWithholding', value)} /></>}
        {input.location.state === 'DE' && <><h3>Delaware withholding and Paid Leave</h3><div className="field-row"><InputField label="Withholding exemptions" prefix="" step="1" value={Number(input.stateOptions?.deExemptions ?? 0)} onChange={value => updateStateOption('deExemptions', value)} /><InputField label="Extra Delaware withholding" value={Number(input.stateOptions?.deExtraWithholding ?? 0)} onChange={value => updateStateOption('deExtraWithholding', value)} /></div><div className="field-row"><InputField label="Employer size" prefix="" step="1" value={Number(input.stateOptions?.deEmployerSize ?? 25)} onChange={value => updateStateOption('deEmployerSize', value)} /><InputField label="Employee share of Paid Leave premium (0–0.5)" prefix="" step="0.01" value={Number(input.stateOptions?.deEmployeeShare ?? .5)} onChange={value => updateStateOption('deEmployeeShare', value)} /></div><p className="help">The default is full coverage at a 50% employee share. Employers with fewer than 25 workers may have a lower rate or no coverage.</p></>}
        {input.location.state === 'RI' && <><h3>Rhode Island RI W-4</h3><div className="field-row"><InputField label="Exemptions" prefix="" step="1" value={Number(input.stateOptions?.riExemptions ?? 0)} onChange={value => updateStateOption('riExemptions', value)} /><InputField label="Extra Rhode Island withholding" value={Number(input.stateOptions?.riExtraWithholding ?? 0)} onChange={value => updateStateOption('riExtraWithholding', value)} /></div><label className="checkbox"><input type="checkbox" checked={!!input.stateOptions?.riExempt} onChange={event => updateStateOption('riExempt', event.target.checked)} />Exempt from Rhode Island income tax withholding</label><p className="help">For the TDI/TCI wage cap, enter YTD Rhode Island taxable wages under YTD values.</p></>}
        {input.location.state === 'LA' && <><h3>Louisiana L-4</h3><label className="checkbox"><input type="checkbox" checked={!!input.stateOptions?.laNoStandardDeduction} onChange={event => updateStateOption('laNoStandardDeduction', event.target.checked)} />Claim no Louisiana standard deduction</label><InputField label="Extra Louisiana withholding" value={Number(input.stateOptions?.laExtraWithholding ?? 0)} onChange={value => updateStateOption('laExtraWithholding', value)} /></>}
        {input.location.state === 'NE' && <><h3>Nebraska W-4N</h3><div className="field-row"><InputField label="Withholding allowances" prefix="" step="1" value={Number(input.stateOptions?.neAllowances ?? 0)} onChange={value => updateStateOption('neAllowances', value)} /><InputField label="Extra Nebraska withholding" value={Number(input.stateOptions?.neExtraWithholding ?? 0)} onChange={value => updateStateOption('neExtraWithholding', value)} /></div></>}
        {input.location.state === 'NY' && <><h3>New York IT-2104</h3><div className="field-row"><InputField label="Allowances" prefix="" step="1" value={Number(input.stateOptions?.nyAllowances ?? 0)} onChange={value => updateStateOption('nyAllowances', value)} /><InputField label="Extra NY withholding" value={Number(input.stateOptions?.nyExtraWithholding ?? 0)} onChange={value => updateStateOption('nyExtraWithholding', value)} /></div><label className="field"><span>City</span><select value={input.location.city ?? ''} onChange={event => update({ ...input, location: { ...input.location, city: event.target.value || undefined } })}><option value="">Outside NYC and Yonkers</option><option value="New York City">New York City</option><option value="Yonkers">Yonkers</option></select></label><label className="checkbox"><input type="checkbox" checked={!!input.stateOptions?.nyPflNotCovered} onChange={event => updateStateOption('nyPflNotCovered', event.target.checked)} />Paid Family Leave does not cover this job</label><InputField label="YTD Paid Family Leave contributions" value={input.ytd?.payrollContributions?.['ny-pfl'] ?? 0} onChange={value => update({ ...input, ytd: { ...input.ytd, payrollContributions: { ...input.ytd?.payrollContributions, 'ny-pfl': value } } })} /></>}
        {input.location.state === 'WA' && <><h3>Washington programs</h3><label className="checkbox"><input type="checkbox" checked={!!input.stateOptions?.waCaresExempt} onChange={event => updateStateOption('waCaresExempt', event.target.checked)} />I have an approved WA Cares exemption</label></>}
      </div>}
      {error && <p className="error" role="alert">{error}</p>}
      <button type="button" className="calculate-button" onClick={submit} disabled={!!error}>Calculate my paycheck <span>→</span></button>
    </section>
    <section className="calculator-card result-card" ref={resultRef} aria-label="Estimated paycheck">
      {error ? <div className="result-unavailable" role="status"><p className="eyebrow">Your estimated paycheck</p><h2>Calculation unavailable</h2><p>Correct the input shown on the left to see an updated paycheck.</p></div> : <>
      <div className="card-heading"><span className="step">02</span><div><p className="eyebrow">Your estimated paycheck</p><h2>{wholeCurrency(result.netPay)} <small>take-home</small></h2></div></div>
      <div className="result-lines"><ResultLine label="Gross pay" amount={result.grossPay} gross /><p className="line-heading">Taxes &amp; payroll deductions</p>{rows.map(row => <ResultLine key={row.label} label={row.label} amount={row.amount} />)}{result.state.payrollDeductions.filter(row => row.amount > 0).map(row => <ResultLine key={row.id} label={row.label} amount={row.amount} />)}{deductions.map(row => <ResultLine key={row.id} label={row.label} amount={row.amount} />)}<div className="net-line"><span>Net pay</span><strong>{currency(result.netPay)}</strong></div></div>
      <div className="keep-callout">You keep approximately <strong>{percent}¢</strong> of every $1 of gross pay.</div>
      <div className="share-row"><button type="button" onClick={shareResult}>Share result</button>{shareStatus && <span role="status">{shareStatus}</span>}</div>
      <div className="periods">{([['Weekly', 'weekly'], ['Biweekly', 'biweekly'], ['Semi-monthly', 'semimonthly'], ['Monthly', 'monthly']] as const).map(([label, frequency]) => <div key={label}><span>{label}</span><strong>{periodResults?.[frequency] ? wholeCurrency(periodResults[frequency].netPay) : '—'}</strong></div>)}<div><span>Annualized</span><strong>{wholeCurrency(result.netPay * periodsPerYear[input.payFrequency])}</strong></div></div><p className="help">Each pay period is calculated separately. A dash means the current per-paycheck deductions exceed pay at that frequency. Annualized pay repeats the selected paycheck; actual yearly totals can differ near wage and contribution limits.</p>
      {!result.local.supported && <p className="local-notice">Local income taxes are not included in this estimate.</p>}
      <p className="verified">Tax rules verified: {result.rules.map(rule => rule.lastVerified).sort().at(0)} · {result.sources.map((source, index) => <span key={source.url}>{index > 0 ? ' · ' : ''}<a href={source.url} target="_blank" rel="noreferrer">{source.authority}</a></span>)}</p>
      <details className="assumptions"><summary>Assumptions and sources</summary><ul>{result.assumptions.map(item => <li key={item}>{item}</li>)}</ul><p>Tax rules verified: {result.rules.map(rule => rule.lastVerified).sort().at(0)}</p><ul>{result.sources.map(source => <li key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.title}</a> — {source.authority}</li>)}</ul></details><p className="disclaimer">Estimated paycheck — not tax advice.</p>
      </>}
    </section>
  </div>;
}
