import { stateCalculators } from '../calculator/states/index.ts';

export const CURRENT_YEAR = 2026;

export const statePages = [
  { code: 'CA', name: 'California', slug: 'california', intro: 'California paychecks can include federal withholding, Social Security, Medicare, state income tax withholding, and State Disability Insurance. The 2026 SDI employee rate is 1.3% of all wages.', note: 'California uses its DE 4 allowances and EDD Method B withholding schedules.' },
  { code: 'TX', name: 'Texas', slug: 'texas', intro: 'Texas does not withhold state individual income tax from wages. A Texas paycheck can still include federal income tax withholding, Social Security, Medicare, and deductions selected through your employer.', note: 'Texas does not have state wage income tax withholding.' },
  { code: 'NY', name: 'New York', slug: 'new-york', intro: 'New York paychecks can include state income tax withholding and Paid Family Leave contributions alongside federal withholding and FICA. New York City and Yonkers residents may also have local withholding.', note: 'The 2026 New York State and Yonkers withholding methods changed on January 1, 2026.' },
  { code: 'FL', name: 'Florida', slug: 'florida', intro: 'Florida does not impose individual income tax on wages. Federal income tax withholding, Social Security, Medicare, and any workplace benefit deductions still affect take-home pay.', note: 'Florida does not have state wage income tax withholding.' },
  { code: 'WA', name: 'Washington', slug: 'washington', intro: 'Washington does not impose state individual income tax on wages, but employee premiums for Paid Family and Medical Leave and WA Cares can reduce take-home pay in addition to federal withholding and FICA.', note: 'The estimate assumes the maximum permitted employee share of Washington Paid Leave premiums.' },
  { code: 'NV', name: 'Nevada', slug: 'nevada', intro: 'Nevada does not withhold individual income tax from paychecks. Federal withholding, Social Security, Medicare, and workplace benefit deductions can still reduce the amount you take home.', note: 'Nevada has no state wage income tax withholding.' },
  { code: 'SD', name: 'South Dakota', slug: 'south-dakota', intro: 'South Dakota has no individual income tax. Federal withholding and FICA remain part of a typical paycheck, along with any deductions selected through an employer.', note: 'South Dakota has no state wage income tax withholding.' },
  { code: 'TN', name: 'Tennessee', slug: 'tennessee', intro: 'Tennessee does not withhold state income tax from earned wages. Your take-home amount still reflects federal income tax withholding, Social Security, Medicare, and selected benefits.', note: 'Tennessee has no state earned-income withholding requirement.' },
  { code: 'NH', name: 'New Hampshire', slug: 'new-hampshire', intro: 'New Hampshire does not tax W-2 wages. A paycheck can still have federal income tax withholding, Social Security, Medicare, and employee benefit deductions.', note: 'New Hampshire has no state wage income tax withholding.' },
  { code: 'WY', name: 'Wyoming', slug: 'wyoming', intro: 'Wyoming does not impose personal state income tax. Federal withholding and payroll taxes, together with any employer benefit deductions, determine take-home pay.', note: 'Wyoming has no state wage income tax withholding.' },
  { code: 'AK', name: 'Alaska', slug: 'alaska', intro: 'Alaska has no state wage income tax, but employees contribute to unemployment insurance. The 2026 employee rate is 0.50% on wages up to the $54,200 state wage base.', note: 'Alaska employee unemployment contributions are shown separately from income taxes.' },
  { code: 'PA', name: 'Pennsylvania', slug: 'pennsylvania', intro: 'Pennsylvania withholds state income tax at 3.07% of taxable compensation and an additional 0.07% employee unemployment contribution in 2026. Many localities also levy earned income or services taxes, which this estimate excludes.', note: 'Traditional 401(k) deferrals remain taxable Pennsylvania compensation. Local taxes are excluded.' },
  { code: 'IL', name: 'Illinois', slug: 'illinois', intro: 'Illinois uses a flat 4.95% withholding rate in 2026 after IL-W-4 allowances. The state publishes a formula method that adjusts each paycheck by the annual allowance value divided by the number of pay periods.', note: 'The calculator uses Illinois IL-700-T formula withholding, including optional IL-W-4 allowances.' },
  { code: 'IN', name: 'Indiana', slug: 'indiana', intro: 'Indiana withholds state income tax at 2.95% in 2026 after applicable WH-4 exemption amounts. County income tax also applies throughout Indiana and depends on the county determined under state rules; county tax is excluded from this estimate.', note: 'Indiana Departmental Notice #1 supplies period-specific exemption constants. County tax is excluded.' },
] as const;

export type StatePage = typeof statePages[number];
export const verifiedStatePages = statePages.filter(page => stateCalculators[CURRENT_YEAR][page.code]?.metadata.status === 'verified');
export const stateBySlug = Object.fromEntries(statePages.map(page => [page.slug, page])) as Record<string, StatePage>;
